# Generated by Django 4.2.2 on 2023-08-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='quiz',
            new_name='quiz_id',
        ),
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_ids', to='quizapp.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_ids', to='quizapp.quiz'),
            preserve_default=False,
        ),
    ]
