# Generated by Django 4.2.2 on 2023-07-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='creator_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
