# Generated by Django 4.2.2 on 2023-07-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_creator_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('content_creator', 'Content Creator')], default='student', max_length=15),
        ),
    ]
