# Generated by Django 4.2.2 on 2023-07-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playlist_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='playlist',
            new_name='playlist_id',
        ),
    ]
