# Generated by Django 4.2.2 on 2023-07-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_creator_id_playlist_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.AlterField(
            model_name='video',
            name='playlist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_ids', to='main.playlist'),
        ),
    ]
