# Generated by Django 4.2.2 on 2023-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_creator_playlist_creator_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist_id',
        ),
        migrations.AddField(
            model_name='video',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='videos/pdf/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='PlayList',
        ),
    ]
