# Generated by Django 4.2.2 on 2023-08-23 21:30

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_book_remove_video_playlist_id_video_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='videos/file/'),
        ),
    ]
