# Generated by Django 4.2.4 on 2023-09-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_video_cover_image_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Topic',
        ),
    ]
